#cloud-config

# install packages
packages:
 - docker
 - openjdk-8-jdk
 - unzip 
 - jq

runcmd:
 - sudo snap remove docker
 - wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
 - sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
 - sudo apt update
 - sudo apt install jenkins -y
 - sudo systemctl start jenkins
 - sudo ufw allow 8080